# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a6f4af584d0e736cbeb40a3edfc38245ad59b74ba56445832ffef192c56087d373b420cd72684b2ccd9edd7d5846272c1c7cd7214b6b9dbed16d8aaf7e1e6b7

test:
  secret_key_base: 902033d7dea774112a473d310b247909a6124f95e871ba0d392eecc48869239e496951e23bee8961c1452ab7babe9aa78712d0eb512f2e24dca710c701021436

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
